class DictXml:
    start = False

    def dumps(self, structure):
        xml = ''
        if not self.start:
            xml = '<?xml version="1.0" encoding="UTF-8"?> \n'
            xml += '<!-- XML generated by London Framework --> \n'
            self.start = True

        for key in structure.keys():
            if isinstance(structure[key], dict):
                xml = '%s<%s>\n%s</%s>\n' % (xml, key, self.dumps(structure[key]), key)
            elif isinstance(structure[key], list):
                xml = '%s<%s>' % (xml, key)
                for item in structure[key]:
                    self.xml = '%s%s' % (xml, self.dumps(item))
                xml = '%s</%s>' % (xml, key)
            else:
                value = structure[key]
                xml = '%s<%s>%s</%s>\n' % (xml, key, value, key)
        return xml

